/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EducationalContentCreateNestedManyWithoutUsersInput } from "./EducationalContentCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { MarketAnalysisCreateNestedManyWithoutUsersInput } from "./MarketAnalysisCreateNestedManyWithoutUsersInput";
import { EnumUserRiskTolerance } from "./EnumUserRiskTolerance";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { StrategyCreateNestedManyWithoutUsersInput } from "./StrategyCreateNestedManyWithoutUsersInput";
import { EnumUserSubscriptionStatus } from "./EnumUserSubscriptionStatus";
import { TradeCreateNestedManyWithoutUsersInput } from "./TradeCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => EducationalContentCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => EducationalContentCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => EducationalContentCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  educationalContents?: EducationalContentCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => MarketAnalysisCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MarketAnalysisCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MarketAnalysisCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  marketAnalyses?: MarketAnalysisCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    enum: EnumUserRiskTolerance,
  })
  @IsEnum(EnumUserRiskTolerance)
  @IsOptional()
  @Field(() => EnumUserRiskTolerance, {
    nullable: true,
  })
  riskTolerance?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => StrategyCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => StrategyCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => StrategyCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  strategies?: StrategyCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    enum: EnumUserSubscriptionStatus,
  })
  @IsEnum(EnumUserSubscriptionStatus)
  @IsOptional()
  @Field(() => EnumUserSubscriptionStatus, {
    nullable: true,
  })
  subscriptionStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => TradeCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TradeCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TradeCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  trades?: TradeCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
