/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StrategyService } from "../strategy.service";
import { StrategyCreateInput } from "./StrategyCreateInput";
import { Strategy } from "./Strategy";
import { StrategyFindManyArgs } from "./StrategyFindManyArgs";
import { StrategyWhereUniqueInput } from "./StrategyWhereUniqueInput";
import { StrategyUpdateInput } from "./StrategyUpdateInput";

export class StrategyControllerBase {
  constructor(protected readonly service: StrategyService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Strategy })
  async createStrategy(
    @common.Body() data: StrategyCreateInput
  ): Promise<Strategy> {
    return await this.service.createStrategy({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Strategy] })
  @ApiNestedQuery(StrategyFindManyArgs)
  async strategies(@common.Req() request: Request): Promise<Strategy[]> {
    const args = plainToClass(StrategyFindManyArgs, request.query);
    return this.service.strategies({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Strategy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async strategy(
    @common.Param() params: StrategyWhereUniqueInput
  ): Promise<Strategy | null> {
    const result = await this.service.strategy({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Strategy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateStrategy(
    @common.Param() params: StrategyWhereUniqueInput,
    @common.Body() data: StrategyUpdateInput
  ): Promise<Strategy | null> {
    try {
      return await this.service.updateStrategy({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Strategy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteStrategy(
    @common.Param() params: StrategyWhereUniqueInput
  ): Promise<Strategy | null> {
    try {
      return await this.service.deleteStrategy({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
